compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[env.staging]
compatibility_flags = ["nodejs_compat"]
[env.staging.vars]
ENVIRONMENT = "staging"

