compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
API_BASE = "https://api.opends.dev"

kv_namespaces = []
r2_buckets = []
d1_databases = []

[env.staging]
compatibility_flags = ["nodejs_compat"]
[env.staging.vars]
ENVIRONMENT = "staging"
API_BASE = "https://staging-api.opends.dev"
